tasks:
  - init: npm install && npm run build:webpack && npm run sequelize:migrate
    command: npm run dev
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
  - port: 6379
    onOpen: ignore
  - port: 5432
    onOpen: ignore